### ISSUE TITLE
environment.yaml specifies old snakemake version

### ISSUE THREAD

**Issue by tanaes** [snakemake/snakemake-tutorial-data#11]
The tutorial steps outlined in the [8.x documentation](https://snakemake.readthedocs.io/en/stable/tutorial/setup.html#step-3-creating-an-environment-with-the-required-software) point to this environment.yaml, which specifies version ≥7.3. Given the breaking changes in architecture with ≥8.0, would it not be preferable to go ahead and update this version requirement?

**Comment by cmeesters** [comment]
yep, just noticed the same. I'm on it, will prepare a PR a.s.a.p.

**Comment by cmeesters** [comment]
not so easy, I'm afraid: pysaml demands a lower Python version, then the current snakemake.

**Comment by johanneskoester** [comment]
We fixed it together.

**Comment by johanneskoester** [comment]
Thanks a lot!
