### ISSUE TITLE
Missing Script

### ISSUE THREAD

**Issue by hakanozadam** [snakemake/snakemake-tutorial-data#7]
In the current version (as of my trial, it is https://github.com/snakemake/snakemake-tutorial-data/tree/2eff276175d23f3b33f8d04346984ae2cd2e61a3 ), the file `scripts/plot-quals.py` is missing which is mentioned in the tutorial in [readthedocs](https://snakemake.readthedocs.io/en/stable/tutorial/basics.html#step-6-using-custom-scripts).

**Comment by johanneskoester** [comment]
That script is to be created by the user during performing the tutorial exercises.
