### ISSUE TITLE
suggest - register graphviz plugins for plotting snakemake DAG

### ISSUE THREAD

**Issue by sbamin** [snakemake/snakemake-tutorial-data#8]
When plotting DAG as in [snakemake tutorial](https://snakemake.readthedocs.io/en/stable/tutorial/basics.html#step-4-indexing-read-alignments-and-visualizing-the-dag-of-jobs), I get an error `Format:_ "png" not recognized. Use one ### of:`.

```sh
snakemake --dag | dot -Tpng > dag.png
```

```
Format: "png" not recognized. Use one of:
Building DAG of jobs...
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

Per [this post](https://stackoverflow.com/a/37297273/1243763), this could be fixed by adding `RUN dot -c && dot -v` in Dockerfile to register required plugins.

Thanks a lot for creating this container - quite useful for teaching software carpentry class on snakemake 101.

**Comment by sbamin** [comment]
@johanneskoester Just created pull request. I am going to close this issue for now.

**Comment by johanneskoester** [comment]
Thanks a lot, just merged!
